version = 1

exclude_patterns = [
  ".yarn/**",
  ".vscode/**",
  ".docusaurus/**",
  ".trunk/out/**",
  "i18n/**",
  "!i18n/en/**",
  "build/**",
  "static/**",
  "node_modules",
  "versions.json",
  "versioned_sidebars/*.json",
  "pnpm-lock.yaml"
]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  plugins = ["react"]