project_id_env: CROWDIN_PROJECT
api_token_env: CROWDIN_TOKEN
base_url: 'https://digitalclouds.crowdin.com'
preserve_hierarchy: true
files:
  - source: /i18n/en/**/*
    translation: /i18n/%two_letters_code%/**/%original_file_name%
  - source: /docs/**/*
    ignore:
      - /docs/ecosystem/**
      - /docs/gallery/**
    translation: /i18n/%two_letters_code%/docusaurus-plugin-content-docs/current/**/%original_file_name%
  - source: /community/**/*
    ignore:
      - /community/01_intro.md
    translation: /i18n/%two_letters_code%/docusaurus-plugin-content-docs-community/current/**/%original_file_name%
