---
blank_issues_enabled: true
contact_links:
  - name: Community Support
    url: https://github.com/z-shell/cummunity/discussions
    about: Please ask and answer questions here.
  - name: Wiki
    url: https://z.digitalclouds.dev
    about: Knowledge Base
