---
name: '♻️ Trunk Check'
on: 
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  trunk_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: trunk-io/trunk-action@v1.0.0
