
---
name: '🥇 Contributors'

on:
  workflow_dispatch:
  pull_request:
    branches: [main]

jobs:
  test-deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    strategy:
      matrix:
        node-version: ['18']
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - uses: pnpm/action-setup@v2.2.1
        with:
          version: 6.32.7
          run_install: |
            - recursive: true
              args: [--no-frozen-lockfile, --strict-peer-dependencies]
      - uses: trunk-io/trunk-action@v1.0.0
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - run: |
          pnpm run crowdin-contributors -p 2 -o digitalclouds -f .github/CONTRIBUTORS.md -t ${{ secrets.CROWDIN_TOKEN }}
