---
name: '🌐 Crowdin Upload'

on:
  workflow_dispatch:
  push:
    branches: ['main']
    paths: ['docs/**', 'community/**', 'src/pages/**', 'blog/**']

env:
  GITHUB_TOKEN: ${{ secrets.GH_PAT }}
  CROWDIN_PROJECT: ${{ secrets.CROWDIN_PROJECT }}
  CROWDIN_TOKEN: ${{ secrets.CROWDIN_TOKEN }}

jobs:
  upload:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    timeout-minutes: 10
    steps:
      - name: '⤵️ Check out code from GitHub'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: '🚀 Crowdin Upload'
        uses: crowdin/github-action@1.4.7
        with:
          upload_sources: true
          # upload_sources_args: '--no-auto-update label=web'
          upload_translations: false
          # auto_approve_imported: false
          # import_eq_suggestions: true
          # upload_translations_args: '--auto-approve-imported --translate-hidden'
          download_translations: false
          push_translations: false
