---
name: '🌐 Crowdin'

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */3 * * *'
  push:
    branches: ['main']
    paths: ['docs/**', 'community/**', 'src/**', 'blog/**']

jobs:
  crowdin-push:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: '⤵️ Check out code from GitHub'
        uses: actions/checkout@v3
      - name: '🚀 Run Crowdin action'
        uses: crowdin/github-action@1.4.7
        with:
          upload_translations: true
          download_translations: false
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          CROWDIN_PROJECT: ${{ secrets.CROWDIN_PROJECT }}
          CROWDIN_TOKEN: ${{ secrets.CROWDIN_TOKEN }}
  crowdin-pull:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: '⤵️ Check out code from GitHub'
        uses: actions/checkout@v3
      - name: '🚀 Run Crowdin action'
        uses: crowdin/github-action@1.4.7
        with:
          upload_translations: false
          download_translations: true
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          CROWDIN_PROJECT: ${{ secrets.CROWDIN_PROJECT }}
          CROWDIN_TOKEN: ${{ secrets.CROWDIN_TOKEN }}   
