---
name: '🌐 Crowdin Download'

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */2 * * *'

env:
  GITHUB_TOKEN: ${{ secrets.GH_PAT }}
  CROWDIN_PROJECT: ${{ secrets.CROWDIN_PROJECT }}
  CROWDIN_TOKEN: ${{ secrets.CROWDIN_TOKEN }}

jobs:
  download:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    timeout-minutes: 10
    steps:
      - name: '⤵️ Check out code from GitHub'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: '🚀 Crowdin Download'
        uses: crowdin/github-action@1.4.7
        with:
          upload_sources: true
          upload_translations: false
          download_translations: true
          skip_untranslated_strings: true
          skip_untranslated_files: false
          export_only_approved: true
          # download_translations_args: '--all --skip-untranslated-strings'
