---
name: '🚀 Deploy'
on:
  workflow_dispatch:
  workflow_run:
    workflows: '♻️ Trunk Check'
    types:
      - completed
jobs:
  deploy:
    timeout-minutes: 15
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest']
        pnpm-version: ['6.32.11']
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v2.2.1
        with:
          version: ${{ matrix.pnpm-version }}
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: pnpm
      - run: |
          pnpm install
          pnpm run build:en
      - run: ${{ secrets.CF_WEBHOOK }}
